#!/bin/bash

#Directory of the main script
script=/bin/chromium-autostart

#Directory of the main script backup
scriptbackup=/bin/chromium-autostart.tmp

#Directory of autostart of Raspberry
lxdepi=/home/pi/.config/lxsession/LXDE-pi/autostart

#Directory of autostart of Raspberry backup
lxdepibackup=/home/pi/.config/lxsession/LXDE-pi/autostart.tmp





clear

cat hexa

sleep 5s


clear

echo "Paste the URL that you want to Chromium auto open"


sleep 1s

read dashboard

if [ -f "$script" ]
then
	cat $script
	echo

	read -p "The file $script already exists, delete? (Y/N)" -n 1 -r
	echo
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
		#CHECK IF BACKUP EXIST
		if [ -f "$scriptbackup" ]
		then
			rm $scriptbackup
		fi
    	mv $script $scriptbackup
      	echo "File moved to $scriptbackup"
      	echo "chromium-browser --noerordialogs --disable-session-crashed-bubble --start-fullscreen --app=$dashboard" > $script
	chmod a+x $script
      	else
		echo "EXITING SCRIPT..."
		exit
	fi
else
	echo "chromium-browser --noerordialogs --disable-session-crashed-bubble --start-fullscreen --app=$dashboard" > $script
	chmod a+x $script
fi



if [ -f "$lxdepi" ]
then
	cat $lxdepi
	echo

	read -p "The file $lxdepi already exists, delete? (Y/N)" -n 1 -r
	echo
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
		if [ -f "$lxdepibackup" ]
		then
			rm $lxdepibackup
		fi
    	mv $lxdepi $lxdepibackup
      echo "File moved to $lxdepibackup"
	fi

fi


echo "@lxpanel --profile LXDE-pi
@pcmanfm --desktop --profile LXDE-pi
@xscreensaver -no-splash
@point-rpi
chromium-autostart" > $lxdepi
chmod a+x $lxdepi



echo "======
$script
======"

more $script

sleep 1s

echo "======
$lxdepi
======"

more $lxdepi
